# Serving
baseurl: "/releaf"
sass:
  style: compressed

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
    values:
      site-title: "Releaf"
  -
    scope:
      path: "documentation"
    values:
      layout: documentation
      group: documentation
